services:
  - type: web
    name: moonai-api
    env: python
    buildCommand: ""
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000